# Generated by Django 5.2.7 on 2025-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='hi', upload_to=''),
            preserve_default=False,
        ),
    ]
